[package]
name = "osunbit"
version = "0.0.1"
edition = "2021"
authors = ["Osunbit"]
description = "Basic Osunbit SDK for Rust"
keywords = ["osunbit", "sdk", "rust"]
license = "MIT"
repository = "https://github.com/osunbit/osunbit_rust_sdk"

[dependencies]
